name: Build and Run PowerShell Script

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: PowerShell/setup-powershell@v0.2.0

      - name: Build and Run PowerShell Script
        run: |
          # Replace 'dev.ps1' with your actual PowerShell script file name
          ./dev.ps1
