name: Manual Trigger for Master Branch

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Your Build Steps
        # Add your build or deployment steps here
