name: Build and Upload Shopify App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        label:
          - label1  # Add your desired label(s) here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

  release-job:
    runs-on: self-hosted

    if: startsWith(github.ref, 'refs/heads/release')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run label2 job
        run: |
          # Add your label2 job command here
          # For example:
          echo "Running label2 job on the new release branch."

      - name: Build React app
        run: npm run build
