name: Build React App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Copy Files
        run: |
          xcopy /E /I C:\Users\vamshi\actions-runner\myworkspace\E-commerce-App_frontend\E-commerce-App_frontend C:\inetpub\wwwroot\dev

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build
