name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: DEV_ENVIRONMENT

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Update this version as needed

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Copy artifact
      run: |
        robocopy /mir /is /it /s /e /ndl /nfl /np /njh /njs build C:\inetpub\wwwroot\dev\
