name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release branch name'
        required: true

jobs:
  release:
    runs-on: windows-latest
    if: github.event_name == 'workflow_dispatch' || contains(github.event.ref, 'refs/heads/release/') && contains(github.event_name, 'push')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check for label-2
        id: check_label
        run: echo "::set-output name=LABEL::$(git log --format=%B -n 1 ${{ github.sha }} | grep -oP '\[label-2\]')"

      - name: Run on label-2
        if: steps.check_label.outputs.LABEL == '[label-2]'
        run: |
          # Your release commands here
          # ...
