name: CI/CD Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - release

jobs:
  label1-job:
    runs-on: self-hosted
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'label1')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run label1 job
        run: npm run label1

  label2-job:
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch' && contains(github.event.client_payload.action, 'label2')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run label2 job
        run: npm run label2
