name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'Label for the runner'
        required: true
        default: 'label-2'

jobs:
  build:
    runs-on: [self-hosted, ${{ github.event.inputs.label }}-runner]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run workflow only on specified label
      if: contains(github.event.inputs.label, 'label-2')
      run: npm run your-release-script
