name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - release/*
      - production/*

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (e.g., production)'
        required: true

jobs:
  deploy_dev:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Dev
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          $destinationDirectory = "C:\inetpub\wwwroot\dev"
          if (!(Test-Path $destinationDirectory)) {
            New-Item -ItemType Directory -Path $destinationDirectory | Out-Null
          }
          Copy-Item -Path ${{ github.workspace }}\* -Destination $destinationDirectory -Recurse -Force
          Write-Host "Deploying to Dev environment"
  deploy_qa:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to QA
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/')
        run: |
          $destinationDirectory = "C:\inetpub\wwwroot\qa"
          if (!(Test-Path $destinationDirectory)) {
            New-Item -ItemType Directory -Path $destinationDirectory | Out-Null
          }
          Copy-Item -Path ${{ github.workspace }}\* -Destination $destinationDirectory -Recurse -Force
          Write-Host "Deploying to QA environment"
  deploy_production:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Production
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/production/')
        run: |
          $destinationDirectory = "C:\inetpub\wwwroot\production"
          if (!(Test-Path $destinationDirectory)) {
            New-Item -ItemType Directory -Path $destinationDirectory | Out-Null
          }
          Copy-Item -Path ${{ github.workspace }}\* -Destination $destinationDirectory -Recurse -Force
          Write-Host "Deploying to Production environment"
