name: CI/CD Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - release

jobs:
  label-job:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run label job
        run: |
          if [[ "${{ runner.labels }}" == *"label1"* ]]; then
            npm run label1
          elif [[ "${{ runner.labels }}" == *"label-2"* ]]; then
            npm run label2
          else
            echo "No matching label found."
          fi
