name: Build and Upload Shopify App (Manual)

on:
  workflow_dispatch:
    branches:
      - release

jobs:
  release:
    runs-on: self-hosted
    strategy:
      matrix:
        label:
          - label-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Copy build artifacts to destination
        run: Copy-Item -Path "C:\Users\vamshi\actions-runner\qaworkspace\E-commerce-App_frontend\E-commerce-App_frontend\build\*" -Destination "C:\inetpub\wwwroot\qa\" -Recurse -Force
