name: Build and Upload Shopify App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Archive build artifacts
        run: |
          # Replace these placeholders with your actual values
          $ArchivePath = "C:\vamshi\shopifyartifacts\shopify.zip"
          $SourcePath = "C:\Users\vamshi\actions-runner\myworkspace\build"
  
          # Ensure the destination path includes a filename
          $ArchiveDestination = Join-Path -Path $ArchivePath -ChildPath "shopify.zip"

          # Create a zip archive
          Compress-Archive -Path $SourcePath -DestinationPath $ArchiveDestination

          # Upload the zip archive as an artifact in the 'shopifyartifacts' folder
          Write-Host "Uploading artifact..."
          Write-Host "##vso[artifact.upload containerfolder=shopifyartifacts;artifactname=shopify]$ArchiveDestination"

# Rest of the workflow...
