name: React CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - labeled
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release branch'
        required: false

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm install

      - name: Build on main with label-1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[label-1]')
        run: |
          npm run build

      - name: Build on release branch with label-2
        if: (github.event_name == 'workflow_dispatch' && contains(github.event.inputs.branch, 'releases/')) || (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/releases/') && contains(github.event.head_commit.message, '[label-2]'))
        run: |
          npm run build
