name: Build and Upload Shopify App

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - release

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        label:
          - label1  # Used for 'master' branch
          - label2  # Used for 'release' branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

  manual-approval:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Manual Approval
        if: github.event_name == 'workflow_run' && matrix.label == 'label2'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Workflow approved'
