name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    types:
      - labeled
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release branch'
        required: false

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm install

      - name: Build on main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          npm run build

      - name: Build on release branch or manually triggered workflow
        if: github.event_name == 'workflow_dispatch' && contains(github.event.inputs.branch, 'releases/')
        run: |
          npm run build
