name: CI/CD Workflow

on:
  push:
    branches:
      - master
      - release

jobs:
  label1-job:
    runs-on: self-hosted
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '[label-1]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run job for label-1 on master
        run: npm run label1-job # replace with your actual build/test command

  release-branch-job:
    runs-on: self-hosted
    if: github.event_name == 'push' && github.ref == 'refs/heads/release' && contains(github.event.head_commit.message, '[label-2]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run job for label-2 on release branch
        run: npm run release-branch-job # replace with your actual build/test command

  manual-trigger-job:
    runs-on: self-hosted
    if: github.event_name == 'workflow_run' && github.event.workflow_run.event == 'manual'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run manual trigger job
        run: npm run manual-trigger-job # replace with your actual deploy/release command
