name: Build and Upload Shopify App

on:
  push:
    branches:
      - master

  workflow_dispatch:
    branches:
      - release
    inputs:
      qa_environment_label:
        description: 'Run on QA_ENVIRONMENT label'
        required: true
        default: 'label2'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        label:
          - label1
          - label2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Copy build artifacts to destination
        run: |
          $buildPath = "C:\Users\vamshi\actions-runner\devworkspace\E-commerce-App_frontend\E-commerce-App_frontend\build\*"
          $destinationPath = if ($env:GITHUB_REF -eq 'refs/heads/release') {
            "C:\inetpub\wwwroot\qa\"
          } else {
            "C:\inetpub\wwwroot\dev\"
          }
          Copy-Item -Path $buildPath -Destination $destinationPath -Recurse -Force
          Write-Host "Build artifacts copied to $destinationPath."

# Add any additional jobs or steps as needed
