name: CI/CD Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - release

jobs:
  build-master:
    runs-on: self-hosted
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build and Test Master Branch
        run: npm run build

  build-release:
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build and Test Release Branch
        run: npm run build
