name: Build and Upload Shopify App

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - release

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        label:
          - label1  # for master branch
          - label-2  # for release_qa_20240205 branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Copy build artifacts to destination
        run: |
          if [ "${{ matrix.label }}" == "label1" ]; then
            cp -r "C:\Users\vamshi\actions-runner\devworkspace\E-commerce-App_frontend\E-commerce-App_frontend\build\*" "C:\inetpub\wwwroot\dev\"
          elif [ "${{ matrix.label }}" == "label-2" ]; then
            cp -r "C:\Users\vamshi\actions-runner\devworkspace\E-commerce-App_frontend\E-commerce-App_frontend\build\*" "C:\inetpub\wwwroot\qa\"
          fi
          
      # Add more steps as needed
