name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    container:
      image: windows-latest
    labels:
      - DEV_ENIRONMENT

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Update this version as needed

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      # Remove the copy step

      # Add other steps as needed...
