name: Build and Upload Shopify App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - release*

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        label:
          - label1  # Add your desired label(s) here for main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Copy build artifacts to destination
        run: |
          if [ ${{ github.event_name }} == 'push' ] && [ ${{ github.ref }} == 'refs/heads/main' ]; then
            Copy-Item -Path "C:\Users\vamshi\actions-runner\devworkspace\E-commerce-App_frontend\E-commerce-App_frontend\build\*" -Destination "C:\inetpub\wwwroot\dev\" -Recurse -Force
          fi

  release:
    needs: build
    runs-on: self-hosted
    strategy:
      matrix:
        label:
          - label2  # Add your desired label(s) here for release

    steps:
      - name: Wait for manual trigger
        uses: srt32/wait-for-workflow-action@v1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Copy build artifacts to destination
        run: |
          if [ ${{ github.event_name }} == 'workflow_dispatch' ] && [[ "${{ github.ref }}" == 'refs/heads/release'* ]]; then
            Copy-Item -Path "C:\Users\vamshi\actions-runner\devworkspace\E-commerce-App_frontend\E-commerce-App_frontend\build\*" -Destination "C:\inetpub\wwwroot\qa\" -Recurse -Force
          fi

      - name: Approve release
        uses: actions/github-script@v5
        with:
          script: |
            const response = await github.rest.actions.createOrUpdateApproval({owner: context.repo.owner, repo: context.repo.repo, pull_number: context.payload.pull_request.number, event: 'APPROVE'})
            console.log(response)
