name: Build and Deploy Shopify App

on:
  push:
    branches:
      - master
      - 'qa*'
      - 'prod'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Run Deployment Script
        shell: pwsh
        run: |
          if ($env:GITHUB_REF -eq 'refs/heads/master') {
            .\dev.ps1
          }
          elseif ($env:GITHUB_REF -match '^refs/heads/qa') {
            .\qa.ps1
          }
          elseif ($env:GITHUB_REF -eq 'refs/heads/prod') {
            .\prod.ps1
          }
